CyberSecurity/Models/QuestionBusinessObject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using CyberSecurity.Interfaces;

namespace CyberSecurity.Models
{
    [Serializable]
    [XmlRoot("Questions"), XmlType("Questions")]
    public class QuestionBusinessObject
    {
        public int QuestionID { get; set; }
        public string QuestionType { get; set; }
        public string QuestionContent { get; set; }
        public int QuestionPriority { get; set; }
        public bool QuestionCheckBox { get; set; }

    }

    public class MalwareQuestionsViewModel : QuestionBusinessObject
    {
        public List<MalwareQuestionsViewModel> ReturnListOfQuestions()
        {
            string xmlData = HttpContext.Current.Server.MapPath("~/App_Data/MalwareQuestions.xml");
            DataSet ds = new DataSet();
            ds.ReadXml(xmlData);
            var questions = new List<MalwareQuestionsViewModel>();
            questions = (from rows in ds.Tables[0].AsEnumerable()
                         select new MalwareQuestionsViewModel
                         {
                             QuestionID = Convert.ToInt32(rows[0].ToString()),
                             QuestionType = rows[1].ToString(),
                             QuestionContent = rows[2].ToString(),
                             QuestionPriority = QuestionPriority = Convert.ToInt32(rows[3].ToString()),
                             QuestionCheckBox = Convert.ToBoolean(rows[4]),
                         }).ToList();
                            return questions;
        }
    }
    public class SecureConfigurationViewModel : QuestionBusinessObject
    {
        public List<SecureConfigurationViewModel> ReturnListOfQuestions()
        {
            string xmlData = HttpContext.Current.Server.MapPath("~/App_Data/SecureConfiguration.xml");
            DataSet ds = new DataSet();
            ds.ReadXml(xmlData);
            var questions = new List<SecureConfigurationViewModel>();
            questions = (from rows in ds.Tables[0].AsEnumerable()
                         select new SecureConfigurationViewModel
                         {
                             QuestionID = Convert.ToInt32(rows[0].ToString()),
                             QuestionType = rows[1].ToString(),
                             QuestionContent = rows[2].ToString(),
                             QuestionPriority = QuestionPriority = Convert.ToInt32(rows[3].ToString()),
                             QuestionCheckBox = Convert.ToBoolean(rows[4]),
                         }).ToList();

                          return questions;
                         }
        }

    public class PatchManagementViewModel: QuestionBusinessObject
    {
        public List<PatchManagementViewModel> ReturnListOfQuestions ()
        {
            string xmlData = HttpContext.Current.Server.MapPath("~/App_Data/PatchManagementQuestions.xml");
            DataSet ds = new DataSet();
            ds.ReadXml(xmlData);
            var questions = new List<PatchManagementViewModel>();
            questions = (from rows in ds.Tables[0].AsEnumerable()
                         select new PatchManagementViewModel
                         {
                             QuestionID = Convert.ToInt32(rows[0].ToString()),
                             QuestionType = rows[1].ToString(),
                             QuestionContent = rows[2].ToString(),
                             QuestionPriority = Convert.ToInt32(rows[3].ToString()),
                             QuestionCheckBox = Convert.ToBoolean(rows[4]),
                         }).ToList();
            return questions;
        }
    }

    public class AccessControlAdminPrivilegeViewModel : QuestionBusinessObject
    {
        public List<AccessControlAdminPrivilegeViewModel> ReturnListOfQuestions()
        {
            string xmlData = HttpContext.Current.Server.MapPath("~/App_Data/AccessControlAdminPrivilegeQuestions.xml");
            DataSet ds = new DataSet();
            ds.ReadXml(xmlData);
            var questions = new List<AccessControlAdminPrivilegeViewModel>();
            questions = (from rows in ds.Tables[0].AsEnumerable()
                         select new AccessControlAdminPrivilegeViewModel
                         {
                             QuestionID = Convert.ToInt32(rows[0].ToString()),
                             QuestionType = rows[1].ToString(),
                             QuestionContent = rows[2].ToString(),
                             QuestionPriority = Convert.ToInt32(rows[3].ToString()),
                             QuestionCheckBox = Convert.ToBoolean(rows[4]),
                         }
                         ).ToList();

            return questions;

        }
    }
}

CyberSecurity/Models/UserBusinessObject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CyberSecurity.Models
{
    public class UserBusinessObject
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userSurname { get; set; }

        public string userEmailAddress { get; set; }

        public char userPassword { get; set; }

    }
}

CyberSecurity/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CyberSecurity.Models
{
    public class UserViewModel
    {
    }
}

CyberSecurity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CyberSecurity.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

CyberSecurity/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Serialization;
using System.Xml.XmlConfiguration;
using System.Xml.Serialization.Configuration;
using System.Xml.Serialization.Advanced;
using System.Xml.Schema;
using System.Xml.XPath;
using System.Data;
using CyberSecurity.Models;

namespace CyberSecurity.Controllers
{
    public class QuestionController : Controller
    {
        // GET: Question
        public ActionResult MalwareQuestion()
        {
            MalwareQuestionsViewModel readXml = new MalwareQuestionsViewModel();

            var data = readXml.ReturnListOfQuestions();

            return View(data.ToList());
        }

        public ActionResult SecureConfigurationQuestion()
        {

            SecureConfigurationViewModel readXml = new SecureConfigurationViewModel();

            var data = readXml.ReturnListOfQuestions();

            return View(data.ToList());
        }

        public ActionResult PatchManagementQuestions()
        {

            PatchManagementViewModel readXml = new PatchManagementViewModel();

            var data = readXml.ReturnListOfQuestions();

            return View(data.ToList());
        }

        public ActionResult AccessControlAdminPrivilegeQuestions()
        {

            AccessControlAdminPrivilegeViewModel readXml = new AccessControlAdminPrivilegeViewModel();

            var data = readXml.ReturnListOfQuestions();

            return View(data.ToList());
        }

    }
}

CyberSecurity/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CyberSecurity.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult LogIn()
        {
            return View();
        }

        public ActionResult RegistrationForm()
        {
            return View();
        }

        public ActionResult ResetPasswordForm()
        {
            return View();
        }

        public ActionResult AssesmentCenter()
        {
            return View();
        }

        public ActionResult ReportGenerator()
        {
            return View();
        }

        public ActionResult LogOutProfile()
        {
            return View();
        }
    }
}

CyberSecurity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h1>About</h1>

<h2>Client details</h2>

<p>Job Title: Professor</p>
<p>Faculty: Faculty of Computer Science</p>
<p>Department: School of Computer Science</p>
<p>Location: David Goldman St Peter's</p>
<p>Contact Details</p>
<p>Telephone:+44(0) 191 515 2053</p>
<a href="mailto:Alistair.Irons@Sunderland.ac.uk?">Send am email</a>
<hr />

<h2>Developer details</h2>
<p>Job Title: Student</p>
<p>Faculty: Faculty of Computer Science</p>
<p>Department: School of Computer Science</p>
<p>Location: David Goldman St Peter's</p>
<p>Contact Details</p>
<p>Telephone: N/A</p>
<a href="mailto:bg54ye@student.sunderldand.ac.uk?">Send an email</a>

CyberSecurity/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h1>Cyber Security Self Assessment</h1>


<p>
    Cras dictum ligula leo, id lobortis orci elementum ut. Sed magna nisl, ultricies nec aliquet maximus, tempus non dolor. 
    Integer ut tellus est. Sed eu lacus sit amet augue fermentum semper eu id urna.
    Ut justo quam, gravida at sapien vel, pharetra vestibulum dui. Nullam consequat fermentum rhoncus. 
    Mauris id ultricies neque, et dictum purus. Aenean dolor augue, vehicula sed ipsum at, ullamcorper maximus ipsum. 
    Curabitur nec massa ac justo dictum finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Fusce congue lacinia magna, at laoreet orci dictum nec. 
    Phasellus quam metus, pretium et sagittis nec, rutrum ac elit. In ut eros ac odio lobortis porta.
    Aliquam faucibus nunc odio, sed varius sem tincidunt sit amet. Integer sit amet ipsum tristique, facilisis massa et, auctor ex. Ut ligula leo, luctus ac velit vitae, consectetur lacinia ipsum.
    Praesent sollicitudin convallis dolor vel aliquam. Pellentesque eget arcu feugiat, iaculis lectus quis, porta lacus. 
    Curabitur suscipit diam diam, ac tristique est consequat ac. Nunc bibendum, lacus ac tempus pellentesque, purus velit fringilla diam, id finibus tellus nulla sit amet tellus
</p>
<hr />
<h2>Prevention matters</h2>

<p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    Aenean vitae urna ut felis sagittis hendrerit in non lacus. In vel metus tempus, pulvinar leo sit amet, eleifend sem.
    Integer non sem feugiat, condimentum lorem id, elementum tellus. Maecenas scelerisque metus at sollicitudin feugiat.
    Vestibulum a auctor massa. In ante quam, facilisis tempus ullamcorper nec, iaculis ut mauris. 
    Donec luctus, dui sed luctus dictum, mi massa pellentesque nisi, id rhoncus est risus vitae sem. 
    Proin efficitur, dui eu gravida dapibus, mi diam malesuada urna, sed congue mi metus eget dui. Donec gravida semper erat ut fermentum. 
    Maecenas nisi quam, rhoncus eget massa ac, eleifend dapibus ipsum. Sed ut velit nisi.
</p>

CyberSecurity/Views/Question/AccessControlAdminPrivilegeQuestions.cshtml
@{
    ViewBag.Title = "MalwareQuestion";
}

<h2>MalwareQuestion</h2>


@using CyberSecurity;
@model IEnumerable<CyberSecurity.Models.QuestionBusinessObject>




<div class="col-lg-8">
    <table class="table table-bordered">
        <tr>
            <th class="alert-info">Number</th>
            <th class="alert-info">Question type</th>
            <th class="alert-info">Question content</th>
            <th class="alert-danger">Priority</th>
            <th class="alert-danger">If applied please tick</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-primary">@Html.DisplayFor(modelItem => item.QuestionID)</td>
                <td class="text-info">@Html.DisplayFor(modelItem => item.QuestionType)</td>
                <td class="text-info">@Html.DisplayFor(modelItem => item.QuestionContent)</td>
                <td class="text-info">@Html.DisplayFor(modelItem => item.QuestionPriority)</td>
                <td class="active">@Html.CheckBoxFor(modelItem => item.QuestionCheckBox)</td>
            </tr>
        }
    </table>
    <btn class="btn-primary">Submit</btn>
</div>

<div class="col-4">
    <table class="table table-responsive">
        <thead>Online tutor</thead>
    </table>
</div>

CyberSecurity/Views/Question/PatchManagementQuestions.cshtml
@{
    ViewBag.Title = "PatchManagementQuestions";
}

<h2>PatchManagementQuestions</h2>

@using CyberSecurity;
@model IEnumerable<CyberSecurity.Models.QuestionBusinessObject>

<div class="col-lg-8">
    <table class="table table-bordered">
        <tr>
            <th class="alert-info">Number</th>
            <th class="alert-info">Question type</th>
            <th class="alert-info">Question content</th>
            <th class="alert-danger">Priority</th>
            <th class="alert-danger">If applied please tick</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionContent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionPriority)
                </td>
                <td>
                    @Html.CheckBoxFor(modelItem => item.QuestionCheckBox)
                </td>
            </tr>
        }
    </table>
    <btn class="btn-primary">Submit</btn>
</div>

CyberSecurity/Views/Question/SecureConfigurationQuestion.cshtml
@{
    ViewBag.Title = "MalwareQuestion";
}

<h2>MalwareQuestion</h2>


@using CyberSecurity;
@model IEnumerable<CyberSecurity.Models.QuestionBusinessObject>




<div class="col-lg-8">
    <table class="table table-bordered">
        <tr>
            <th class="alert-info">Number</th>
            <th class="alert-info">Question type</th>
            <th class="alert-info">Question content</th>
            <th class="alert-danger">Priority</th>
            <th class="alert-danger">If applied please tick</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionContent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionPriority)
                </td>
                <td>
                    @Html.CheckBoxFor(modelItem => item.QuestionCheckBox)
                </td>
            </tr>
        }
    </table>
    <btn class="btn-primary">Submit</btn>
</div>

CyberSecurity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cyber Security Online Assessment</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <li>@Html.ActionLink("Assesment Center", "AssesmentCenter", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("New user", "RegistrationForm", "User", new { area = "" }, new { @class = "navbar-brand" })</li>   
                    <li>@Html.ActionLink("Log in", "LogIn", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cyber Security Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CyberSecurity/Views/User/AssesmentCenter.cshtml
@{
    ViewBag.Title = "AssesmentCenter";
}

<h1 style="text-align:center">AssesmentCenter</h1>

<hr/>

<p>
   Mauris et fringilla dui. Etiam nec porttitor velit. Phasellus suscipit scelerisque risus et bibendum.
   Fusce sodales faucibus sem, eget feugiat magna euismod id. Donec sit amet lacus vitae ligula rutrum porta.
   Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
   Nullam efficitur, urna nec fringilla euismod, erat sapien blandit tellus, non porta nisi libero quis enim.
   Nulla sed mi vitae ante lacinia pellentesque sed vel nibh. Suspendisse eget libero posuere ipsum ornare vestibulum. 
   Suspendisse eget nunc purus. Nunc aliquam tortor eu nisl varius lobortis. Nullam et mauris lectus.
</p>


@Html.ActionLink("Malware", "MalwareQuestion", "Question")
@Html.ActionLink("Secure Configuration", "SecureConfigurationQuestion", "Question")
@Html.ActionLink("Patch Management", "PatchManagementQuestions", "Question")
@Html.ActionLink("Access Control and Administrative Privilege", "AccessControlAdminPrivilegeQuestions", "Question")
@Html.ActionLink("Boundary Firewallls and Internet Gateways", "BoundaryFirewallsInternetGateways", "Question")




@Html.ActionLink("Report generator", "ReportGenerator", "User")

CyberSecurity/Views/User/LogIn.cshtml
@{
    ViewBag.Title = "LogInForm";
}

<h2 style="text-align:center">Log in</h2

@Html.BeginForm(){ 

}
<br />
@Html.ActionLink("Forgotten password?", "ResetPasswordForm", "User")
<br />
@Html.ActionLink("Not registered", "RegistrationForm", "User")

CyberSecurity/Views/User/RegistrationForm.cshtml
@{
    ViewBag.Title = "RegistrationForm";
}

<h2>Register</h2>

CyberSecurity/Views/User/ReportGenerator.cshtml
@{
    ViewBag.Title = "ReportGenerator";
}

<h2>ReportGenerator</h2>

CyberSecurity/Views/User/ResetPasswordForm.cshtml
@{
    ViewBag.Title = "ResetPasswordForm";
}

<h2>ResetPasswordForm</h2>


@using (Html.BeginForm("Search", "YOUR CONTROLLER", FormMethod.Post))
{
 
    <p>@Html.TextBox("Enter username:")</p>
  
} 
@Html.DisplayText("Enter your username:")